apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rcs-ocm-addons.fullname" . }}-capp-status-addon
  labels:
  {{- include "rcs-ocm-addons.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rcs-ocm-addons.fullname" . }}-capp-status-addon
subjects:
  - kind: ServiceAccount
    name: {{ include "rcs-ocm-addons.fullname" . }}-capp-status-sa
    namespace: {{ .Release.Namespace }}