kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .AddonName }}
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: {{ .AddonName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .AddonName }}
  template:
    metadata:
      labels:
        app: {{ .AddonName }}
    spec:
      serviceAccountName: {{ .AgentServiceAccountName }}
{{- if .NodeSelector }}
      nodeSelector:
      {{- range $key, $value := .NodeSelector }}
        "{{ $key }}": "{{ $value }}"
      {{- end }}
{{- end }}
{{- if .Tolerations }}
      tolerations:
      {{- range $toleration := .Tolerations }}
      - key: "{{ $toleration.Key }}"
        value: "{{ $toleration.Value }}"
        effect: "{{ $toleration.Effect }}"
        operator: "{{ $toleration.Operator }}"
        {{- if $toleration.TolerationSeconds }}
        tolerationSeconds: {{ $toleration.TolerationSeconds }}
        {{- end }}
      {{- end }}
{{- end }}
      volumes:
      - name: hub-config
        secret:
          secretName: {{ .KubeConfigSecret }}
      containers:
      - name: {{ .AddonName }}
        image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        env:
        {{- if .MAX_CPU_COUNT }}
          - name: MAX_CPU_COUNT
            value: "{{ .MAX_CPU_COUNT }}"
        {{- end }}
        {{- if .MIN_CPU_COUNT }}
          - name: MIN_CPU_COUNT
            value: "{{ .MIN_CPU_COUNT }}"
        {{- end }}
        {{- if .MAX_MEMORY_BYTES }}
          - name: MAX_MEMORY_BYTES
            value: "{{ .MAX_MEMORY_BYTES }}"
        {{- end }}
        {{- if .MIN_MEMORY_BYTES }}
          - name: MIN_MEMORY_BYTES
            value: "{{ .MIN_MEMORY_BYTES }}"
        {{- end }}
  {{- if or .HTTPProxy .HTTPSProxy}}
        {{- if .HTTPProxy }}
          - name: HTTP_PROXY
            value: {{ .HTTPProxy }}
        {{- end }}
        {{- if .HTTPSProxy }}
          - name: HTTPS_PROXY
            value: {{ .HTTPSProxy }}
        {{- end }}
        {{- if .NoProxy }}
          - name: NO_PROXY
            value: {{ .NoProxy }}
        {{- end }}
{{- end }}
        command:
          - "/score-addon"
        args:
          - "agent"
          - "--hub-kubeconfig=/var/run/hub/kubeconfig"
          - "--cluster-name={{ .ClusterName }}"
          - "--addon-namespace={{ .AddonInstallNamespace }}"
        volumeMounts:
          - name: hub-config
            mountPath: /var/run/hub