kind: Deployment
apiVersion: apps/v1
metadata:
  name: rcs-score-addon-manager
spec:
  template:
    spec:
      containers:
        - name: rcs-score-addon-manager
          env:
            - name: ADDON_IMAGE
              value: $(ADDON_IMAGE)