apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: rcs-score
  annotations:
    addon.open-cluster-management.io/lifecycle: "addon-manager"
spec:
  addOnMeta:
    displayName: Resource Usage Collect Addon
    description: "rcs-score-addon is an example addon that generate addonplacementscore for each managed cluster"