namespace: open-cluster-management

resources:
- manager.yaml
- clustermanagementaddon.yaml
- ../rbac

images:
- name: controller
  newName: controller
  newTag: latest

patches:
- path: addon_manager_env_var_patch.yaml

replacements:
- source:
    fieldPath: .spec.template.spec.containers.0.image
    group: apps
    kind: Deployment
    name: rcs-score-addon-manager
    version: v1
  targets:
  - fieldPaths:
    - .spec.template.spec.containers.0.env.0.value
    options:
      create: true
      delimiter: /
    select:
      kind: Deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
