kind: Deployment
apiVersion: apps/v1
metadata:
  name: rcs-score-addon-manager
  labels:
    app: rcs-score-addon-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rcs-score-addon-manager
  template:
    metadata:
      labels:
        app: rcs-score-addon-manager
    spec:
      serviceAccountName: rcs-score-addon-sa
      containers:
      - name: rcs-score-addon-manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        command:
          - "/score-addon"
        args:
          - "manager"
