apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .RoleAndRolebindingName }}
rules:
  - apiGroups:
      - rcs.dana.io
    resources:
      - capps
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - rcs.dana.io
    resources:
      - capps/status
    verbs:
      - get
      - patch
      - update