kind: Deployment
apiVersion: apps/v1
metadata:
  name: capp-status-addon
  labels:
    app: capp-status-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capp-status-addon
  template:
    metadata:
      labels:
        app: capp-status-addon
    spec:
      serviceAccountName: capp-status-addon-sa
      containers:
      - name: capp-status-addon
        image: controller:latest
        imagePullPolicy: IfNotPresent
        command:
          - /status-addon
        args:
          - "manager"